# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jdlm.info
description: > # this means to ignore newlines until "baseurl:"
  John Lees-Miller's personal website, such as it is.
  Develop the lessons and pass them on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jdlm.info" # the base hostname & protocol for your site
twitter_username: jdleesmiller
github_username: jdleesmiller

# Build settings
markdown: kramdown
